# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "hello app"
  homepage "https://github.com/rvigo/homebrew-hello"
  version "1.6.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_arm64.tar.gz"
      sha256 "3deb9ef0da6420a8065c01066613efca1c1a48209de58c3c7b53c4879bba193d"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_x86_64.tar.gz"
      sha256 "05b8138359aec171ea11bc8bc2d60262e92827f4ef91fa573ca3c6303ff6721e"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_x86_64.tar.gz"
      sha256 "428aa40e26976fa36b413e339c87c3fa9a6114dd369d30368c400c2b27207aa2"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_arm64.tar.gz"
      sha256 "3a75a171f6902c89e0fc8a6bf5df484a604e6ebc940819ec9916879379e90dce"

      def install
        bin.install "hello"
      end
    end
  end
end
