# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "hello app"
  homepage "https://github.com/rvigo/homebrew-hello"
  version "1.6.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_x86_64.tar.gz"
      sha256 "8de3292e9de6a52fd5d0d9b527c2711ff9e092879d7c6e90c7a3556c85b980b3"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_arm64.tar.gz"
      sha256 "3b5851d1a581d5c2449cf1502bdfbccfe93ecd57b36ceecdac9777262e62d8e1"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_arm64.tar.gz"
      sha256 "f6171357a11287b8c642479473f5611e33f254e563a854946fc6651decd693c5"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_x86_64.tar.gz"
      sha256 "9afceace4d0abfd3e5bd671ffefb9b77d340b50f44d8c63e354d6fa03478500f"

      def install
        bin.install "hello"
      end
    end
  end
end
