# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hello < Formula
  desc "hello app"
  homepage "https://github.com/rvigo/homebrew-hello"
  version "1.6.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_arm64.tar.gz"
      sha256 "a0c0fdbcac31a8fcfbde99813f938a7e22a63a19df5c12579ddcba16c6d71c15"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_darwin_x86_64.tar.gz"
      sha256 "6f3da4b248c1dccfff70e4f5d9eb39f2e9d7ee0bd926d4fd24b2eab4b9b97c04"

      def install
        bin.install "hello"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_x86_64.tar.gz"
      sha256 "74c8d59bf76754f080101f0fb72ab4e2b8c1207846b340f1524324afc21bfece"

      def install
        bin.install "hello"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rvigo/hello/releases/download/v1.6.7/hello_1.6.7_linux_arm64.tar.gz"
      sha256 "f6275abce5a5777f0dfb8123cb36dcaca69ba303c46df8d0d84373e13cbdb2ea"

      def install
        bin.install "hello"
      end
    end
  end
end
